---
- name: Emergency DNF repair on all hosts
  hosts: all
  become: yes
  gather_facts: no

  tasks:

    - name: Stop and disable dnf-makecache timer
      systemd:
        name: dnf-makecache.timer
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Remove DNF cache directory
      file:
        path: /var/cache/dnf
        state: absent

    - name: Recreate DNF cache directory
      file:
        path: /var/cache/dnf
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Remove DNF lib metadata
      file:
        path: /var/lib/dnf
        state: absent

    - name: Recreate DNF lib directory
      file:
        path: /var/lib/dnf
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Remove RPM database temporary files
      shell: rm -f /var/lib/rpm/__db*
      become: yes

    - name: Rebuild RPM database
      command: rpm --rebuilddb
      become: yes

    - name: Ensure sane /etc/dnf/dnf.conf
      copy:
        dest: /etc/dnf/dnf.conf
        owner: root
        group: root
        mode: '0644'
        content: |
          [main]
          gpgcheck=1
          installonly_limit=3
          clean_requirements_on_remove=True
          best=True
          skip_if_unavailable=True
          module_platform_id=platform:el9
          module_hotfixes=true

    - name: Clean all DNF metadata
      command: dnf clean all
