---
- name: Fix AppStream module metadata safely              # “один пакет капризничает”
  hosts: all
  become: yes
  gather_facts: false

  tasks:
    - name: Stop and mask dnf-makecache.timer
      systemd:
        name: dnf-makecache.timer
        state: stopped
        enabled: no
        masked: yes

    - name: Remove DNF cache
      file:
        path: /var/cache/dnf
        state: absent

    - name: Recreate DNF cache directory
      file:
        path: /var/cache/dnf
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Remove DNF lib metadata
      file:
        path: /var/lib/dnf
        state: absent

    - name: Recreate DNF lib directory
      file:
        path: /var/lib/dnf
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Remove RPM temporary DB files
      shell: rm -f /var/lib/rpm/__db*
      args:
        warn: false

    - name: Rebuild RPM database
      command: rpm --rebuilddb

    - name: Force sane dnf.conf (disable modules)
      copy:
        dest: /etc/dnf/dnf.conf
        content: |
          [main]
          gpgcheck=1
          installonly_limit=3
          clean_requirements_on_remove=True
          best=True
          skip_if_unavailable=True
          module_platform_id=platform:el9
          modules_enabled=0
          module_hotfixes=true

    - name: Clean DNF metadata
      command: dnf clean all
